
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ThemeProvider} from "@/components/theme-provider";
import { Layout } from "@/components/layout";
import { Providers } from "@/redux/provider";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Providers>
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Layout>
              {children}
          </Layout>
      </ThemeProvider>
      </body>
    </Providers>
    </html>
  )
}
