
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ThemeProvider} from "@/components/theme-provider";
import LayoutProvider  from "@/app/layoutProvider";
import { Providers } from "@/redux/provider";
import React from "react";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
    <Providers>
      <body className={inter.className}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <LayoutProvider>
              {children}
          </LayoutProvider>
      </ThemeProvider>
      </body>
    </Providers>
    </html>
  )
}
